package com.study2minute.utils;

public class Constants {
	public static final String DRIVER_URL = "org.apache.derby.jdbc.EmbeddedDriver";
	public static final String DB_PATH = "/home/mrinal/PracticeDB";
	public static final String CONNECTION_URL = "jdbc:derby:" + DB_PATH + ";create = true;";
	
	public static final String CREATE_CATAGORY_TBL = "CREATE TABLE CATAGORY_TBL (CATAGORY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), CATAGORY_NAME VARCHAR(50) NOT NULL, PRIMARY KEY(CATAGORY_ID))";
	public static final String CREATE_SUBCATAGORY_TBL = "CREATE TABLE SUBCATAGORY_TBL (SUBCATAGORY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), SUBCATAGORY_NAME VARCHAR(100) NOT NULL, PARENT_CATAGORY_ID INTEGER NOT NULL, PRIMARY KEY(SUBCATAGORY_ID), FOREIGN KEY(PARENT_CATAGORY_ID) REFERENCES CATAGORY_TBL)";
	
	public static final String INSERT_CATAGORY_TBL = "INSERT INTO CATAGORY_TBL(CATAGORY_NAME) VALUES(?)";
	public static final String INSERT_SUBCATAGORY_TBL = "INSERT INTO SUBCATAGORY_TBL (SUBCATAGORY_NAME, PARENT_CATAGORY_ID) VALUES(?,?)";
	
	public static final String CREATE_AUTHOR_TBL = "CREATE TABLE AUTHOR_TBL (AUTHOR_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), AUTHOR_NAME VARCHAR(50) NOT NULL, PHONE_NUMBER VARCHAR(13) NOT NULL, EMAIL_ID VARCHAR(50) NOT NULL, BANK_NAME VARCHAR(100) NOT NULL, BRANCH_NAME VARCHAR(60) NOT NULL, ACCOUNT_NUMBER VARCHAR(50) NOT NULL, ACCOUNT_TYPE VARCHAR(25) NOT NULL, IFSC_NUMBER VARCHAR(50) NOT NULL, PRIMARY KEY(AUTHOR_ID))";
	public static final String CREATE_ARTICLE_TBL = "CREATE TABLE ARTICLE_TBL (ARTICLE_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),SUBCATAGORY_ID INTEGER NOT NULL, ARTICLE_TITLE VARCHAR(150) NOT NULL, AUTHOR_ID INTEGER NOT NULL,UPLOAD_TIME TIMESTAMP NOT NULL, HITCOUNT INTEGER NOT NULL DEFAULT 0, UPVOTE INTEGER NOT NULL DEFAULT 0, DOWNVOTE INTEGER NOT NULL DEFAULT 0, PDF_LOC VARCHAR(200) DEFAULT NULL, PRIMARY KEY(ARTICLE_ID), FOREIGN KEY(SUBCATAGORY_ID) REFERENCES SUBCATAGORY_TBL, FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR_TBL)";
	
	public static final String INSERT_AUTHOR_TBL = "INSERT INTO AUTHOR_TBL(AUTHOR_NAME, PHONE_NUMBER, EMAIL_ID, BANK_NAME, BRANCH_NAME, ACCOUNT_NUMBER, ACCOUNT_TYPE, IFSC_NUMBER) VALUES(?,?,?,?,?,?,?,?)";
	public static final String INSERT_ARTICLE_TBL = "INSERT INTO ARTICLE_TBL(SUBCATAGORY_ID, ARTICLE_TITLE, AUTHOR_ID, UPLOAD_TIME, PDF_LOC) VALUES(?,?,?,?,?)";
	
	public static final String SELECT_ALL_CATEGORY = "select * from CATAGORY_TBL";
	public static final String SELECT_ALL_SUBCATAGORY = "SELECT * FROM SUBCATAGORY_TBL";
	public static final String SELECT_ALL_AUTHOR = "SELECT * FROM AUTHOR_TBL";
	public static final String SELECT_ALL_ARTICLE = "SELECT * FROM ARTICLE_TBL";
	
	public static final String SELECT_CATAGORY = "SELECT CATAGORY_NAME FROM CATAGORY_TBL";
	public static final String SELECT_CATAGORY_NAME_GIVEN_CATAGORY_ID = "select catagory_name from CATAGORY_TBL where catagory_id=?";
	public static final String SELECT_CATAGORY_ID_GIVEN_SUBCATAGORY_ID = "select parent_catagory_id from SUBCATAGORY_TBL where subcatagory_id=?";
	public static final String SELECT_SUBCATAGORY_NAME_GIVEN_SUBCATAGORY_ID = "select subcatagory_name from SUBCATAGORY_TBL where subcatagory_id=?";
	public static final String SELECT_CATAGORY_ID_GIVEN_CATAGORY_NAME = "SELECT CATAGORY_ID FROM CATAGORY_TBL WHERE CATAGORY_NAME=?";
	public static final String SELECT_SUBCATAGORY_NAME_GIVEN_PARENT_CATAGORY_ID = "select subcatagory_name from SUBCATAGORY_TBL where parent_catagory_id=?";
	public static final String SELECT_SUBCATAGORY_NAME_SUBCATAGORY_ID_GIVEN_PARENT_CATAGORY_ID = "select subcatagory_name,subcatagory_id from SUBCATAGORY_TBL where parent_catagory_id=?";
	public static final String SELECT_AUTHOR_NAME_GIVEN_AUTHOR_ID = "SELECT AUTHOR_NAME FROM AUTHOR_TBL WHERE AUTHOR_ID = ?";
	public static final String GET_ARTICLE_LIST_FROM_SUBCATAGORY_ID = "SELECT ARTICLE_TITLE, HITCOUNT, UPVOTE, DOWNVOTE,AUTHOR_ID,PDF_LOC FROM ARTICLE_TBL where SUBCATAGORY_ID=?";

	
	public static final String GET_ALL_DETAILS_FROM_ARTICLE_ID = "select * from ARTICLE_TBL where ARTICLE_ID=?";
	public static final String GET_ARTICLE_LIST_FROM_AUTHOR_ID = "SELECT ARTICLE_ID, SUBCATAGORY_ID, ARTICLE_TITLE, UPLOAD_TIME, HITCOUNT, UPVOTE, DOWNVOTE FROM ARTICLE_TBL where AUTHOR_ID=?";
	public static final String GET_AUTHOR_DETAILS_FROM_AUTHOR_ID = "SELECT AUTHOR_NAME, PHONE_NUMBER, EMAIL_ID, BANK_NAME, BRANCH_NAME, ACCOUNT_NUMBER, ACCOUNT_TYPE, IFSC_NUMBER FROM AUTHOR_TABLE WHERE AUTHOR_ID = ?";
	
	public static final String GET_MOST_10_POPULAR_ARTICLE = "SELECT article_id,ARTICLE_TITLE FROM ARTICLE_TBL order by UPVOTE-DOWNVOTE desc fetch first 10 rows only";
	public static final String GET_MOST_10_READ_ARTICLE = "SELECT article_id,ARTICLE_TITLE FROM ARTICLE_TBL order by HITCOUNT desc fetch first 10 rows only;";
	
	public static final String UPLOAD_PATH = "/home/mrinal/Upload-Path";
}